language: android
jdk: oraclejdk11
os: linux
dist: trusty
env:
  global:
  - secure: P2lwchfMfFJvZZMX01RzGoDGaelzLm+JO0En1SJ65c6nqSeNGJlMAQW+xjtfkQsREj1ksuPPLvzKyTjl9uVmot7f2dHM04dpUiOHafRcNVpV4oezJSN638EEPGP1cKiRA1KRzosqXAQlKRqVHtwq4aXGkte0wwWP1so6PS0Ob6782NOgPOP8rNN6hNVmOn9Kwtjfwg8WOPXuFRdB3nf/j/OwiDsp8ipgHJqrl5X/JttFkSOxMfm06C9d0v7Ae6OK3cNyQ3QI2ICnvY7gyCcmV/Dc+dhGkTBFgR4wr9Tq1NdoeC6mDiLcteugq/1blc/PhFFu6N2QuY7wMjeBW+Rk0dY3XtdqgAV6/QPX6LlafqJ2Ja0X7QzXLAbyxDIVb5XfwhSFYD3uR/T9yseHnoBIKboFszxXPy9j8I1qI/Hk4bsWAXQ/5iy+I+ngkZngfN8tMvHen8ovNMRx0qXa8zPK1pEInY0c5i/kvTVHwdIz8ejAzytDjdi+Ep6iTaZXa54GsFpfhH1ePnC2a1rZGzEwAkfG5sd2zZAZhkHDSyjIRjb1nhOHcuXHKtaIFwUypcduFFi+3vdnkmsypmTw+uS6URKtPXa4MiPpF1mxpKZe8n+Y/yWTzgd+qmu4uOqP2+46R0hGkpq5wFlfGEyP6kiEFDYQk1hOasSRCxI6l0VBb3M=
android:
  components:
  - android-30
  - tools
  - platform-tools
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
  - mkdir -p $HOME/android-cmdline-tools
  # Download and unzip the Android command line tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-cmdline-tools/cmdline-tools.zip ; then curl "https://dl.google.com/android/repository/commandlinetools-linux-${COMMAND_LINE_TOOLS_VERSION}_latest.zip" > $HOME/android-cmdline-tools/cmdline-tools.zip ; fi
  - unzip -qq -n $HOME/android-cmdline-tools/cmdline-tools.zip -d $HOME/android-cmdline-tools
  - echo y | $HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools"
  - echo y | $HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;${BUILD_TOOLS_VERSION}"
  - echo y | $HOME/android-cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-${TARGET_SDK_VERSION}"

  # To see if the correct values have been extracted.
  - echo TARGET_SDK_VERSION=$TARGET_SDK_VERSION
  - echo BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION

  # Ensure Gradle wrapper is executable
  - chmod +x gradlew

jobs:
  include:
  - name: Staging
    script: ./gradlew assembleRelease

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  - $HOME/android-cmdline-tools
  - $HOME/android-sdk
