version: 2.1

references:
  ## Workspace
  workspace: &workspace
               ~/code

  ## Docker image configuration
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-30-node
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false -Dorg.gradle.daemon=false'
  ## Cache
  gradle_key: &gradle_key
                jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  ## Dependencies
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  store_artifacts: &store_artifacts
    store_artifacts:
      path: app/build/outputs/apk
      destination: apk

  #Install and login appcenter
  login_appcenter: &login_appcenter
    run:
      name: Login appcenter
      command: |
        sudo npm install appcenter-cli -g
        appcenter login --token $APPCENTER_TOKEN --disable-telemetry

  save_secrets: &save_secrets
    run:
      name: Save secrets from env to file
      command: |
        echo "build_number=<< pipeline.number >>" >> secrets.properties

  git_commit_message: &git_commit_message
    run:
      name: Gets commit message
      command: |
        GIT_COMMIT_DESC=$(git log --format=%B -n 1 "$CIRCLE_SHA1")
        echo 'export GIT_COMMIT_DESC="$GIT_COMMIT_DESC"' >> $BASH_ENV

jobs:
  build:
    <<: *android_config
    steps:
      - checkout:
          path: *workspace
      - *save_secrets
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Build for proper environment
          command: |
            ./gradlew clean assembleRelease

      - *store_artifacts
  push_to_appcenter:
    <<: *android_config
    steps:
      - checkout:
          path: *workspace
      - attach_workspace:
          at: *workspace
      #      - *git_commit_message
      - *login_appcenter
      - run:
          name: Detect version type, Change version and Publish
          command: |
            GIT_COMMIT_DESC=$(git log --format=%B -n 1 "$CIRCLE_SHA1")
            echo $GIT_COMMIT_DESC
      - run:
          name: Push to appcenter
          command: |
            GIT_COMMIT_DESC=$(git log --format=%B -n 1 "$CIRCLE_SHA1")
            appcenter distribute release release-notes "${$GIT_COMMIT_DESC}" --app sud_test/hopin --file app/build/outputs/apk/release/app-release.apk --group "Testers"

workflows:
  build-app:
    jobs:
      - build
      - push_to_appcenter:
          requires:
            - build
