# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy to firebase distribution"
  lane :distribute do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
          app: "1:216383642083:android:24d7efbe9e23f4c1",
          groups: "testers",
          release_notes: "Lots of amazing new features to test out!"
      )
  end
end
